# Generated by Django 2.2 on 2019-04-15 14:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter attraction's name.", max_length=200, verbose_name='Name')),
                ('description', models.TextField(max_length=500)),
                ('timeNeededToSightsee', models.FloatField(verbose_name='Time neede to sightsee (in hours)')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Name of the street', max_length=100, verbose_name='Street')),
                ('zipCode', models.CharField(help_text='Zip code', max_length=10, verbose_name='Zipcode')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('voivodeship', models.CharField(max_length=50, verbose_name='Voivodeship')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.ManyToManyField(to='guide.Attraction', verbose_name='Attraction list')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Client', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.ManyToManyField(to='guide.Attraction', verbose_name='Attraction list')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Client', verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ManyToManyField(to='guide.Category'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='localizations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.Localization', verbose_name='Address'),
        ),
    ]
